scrape_configs:
  - job_name: 'user-service'
    metrics_path: '/user-service/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['host.docker.internal:8000']
  - job_name: 'apigateway-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['host.docker.internal:8000']
  - job_name: 'order-service'
    metrics_path: '/order-service/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['host.docker.internal:8000']
