#변경2
token:
  expiration_time: 86400002
  secret: '{cipher}AQBk9vhkciyrA3+SZEHyKZ43nvs+8DxwcodwOl8sEIy+tmrbh6mQctClnaNkyqLprGyS6ogRhXHCE9hvyaz7wAb12QYdKla3jYL04WefERX3R+R6PtCdp+AjylEJK2aw+YW9EZYuIF7XWzXFHrfOpiz66CTRhofjPRmdprQUWJgfUt0hyuYilIbkv18nb6kaxUaSC8mSYqvwv6DZeZBZRcsntPN1rYpIovIy2/fEBQ0sMax75os/eFB/CCmS3W00MSTnJoYxmOiaRzMjLoHPSqj3CuZBhKdqEO18PN1MxO+bAIn5c07ADVpz/pE+EWqh3VsHNYpcUdcT3wi9BEI9f4Qis3m/LUiPZguI3jNGIUuzsgjiEW7sWkndq1XrewtoIIURRHQ8tSjyRuVP1KlCoWtBzqK8nurmgG0Sq5r1WIF2zi8kSTbxi8jMLTgLWgMWM6cifB2Bg3/e453OeZ8w4STu'

gateway:
  ip: 192.168.123.100

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: '{cipher}AQCr3XsiItFqb0q6ue/Cr0CSRDj1WQ6lgYLpW8qkqD8MBrASNgBNQcwKUNf+P3ZcsYy/WycCa5NAXGn5aAlZUsZMu66X5xPUcTvnxzUP0G6H3YQN4w5mmVwGKtgVfHSektXuhivC/S0dlzPb7oKzgvt7N3TAHU7hef5hdHQPodxt6kLTY0nUV95DxFbBa+QwUFIula4vTUWlKAYRERPE6f3WSsQ1XT8wytdJASE3r9OxtEBC/8qn7/K4NRCoPMjvgfRKFcZh0w+OLOIHdXlxDBs4xyurlfORb4L+K+YFWpFxJWnP7IEIPQAQpyolDfSHsVfdoddlZRS4xpb/yXaxBArdU6L7MT8MlNNC1tDKOUF4dIHjYUGAzlia5/RwDIJgYPs='
    
order_service:
  url: http://127.0.0.1:8000/order-service/%s/orders